version: 2.1

orbs:
  buildevents: honeycombio/buildevents@0.9.0

executors:
  python:
    docker:
      - image: cimg/python:3.8
  github:
    docker:
      - image: cibuilds/github:0.13.0

commands:
  setup:
    steps:
      - checkout
      - buildevents/berun:
          bename: poetry_install
          becommand: poetry install --no-root --no-ansi
  run_lint:
    steps:
      - buildevents/berun:
          bename: run_lint
          becommand: poetry run pylint --rcfile=pylint.rc libhoney
      - buildevents/berun:
          bename: run_pycodestyle
          becommand: poetry run pycodestyle libhoney --max-line-length=140
  run_tests:
    steps:
      - buildevents/berun:
          bename: run_tests
          becommand: poetry run coverage run -m unittest discover -v
  run_coverage:
    steps:
      - buildevents/berun:
          bename: coverage_report
          becommand: poetry run coverage report --include="libhoney/*"
      - buildevents/berun:
          bename: coverage_html
          becommand: poetry run coverage html --include="libhoney/*"

  runtests:
    steps:
      - setup
      - run_lint
      - run_tests
      - run_coverage
      - store_artifacts:
          path: htmlcov
  build:
    steps:
      - setup
      - run: mkdir -p ~/artifacts
      - buildevents/berun:
          bename: poetry_build
          becommand: poetry build
      - buildevents/berun:
          bename: copy_binaries
          becommand: cp dist/* ~/artifacts
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts
      - store_artifacts:
          path: ~/artifacts

  publish_github:
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Artifacts being published"
          command: |
            echo "about to publish to tag ${CIRCLE_TAG}"
            ls -l ~/artifacts/*
      - buildevents/berun:
          bename: ghr_draft
          becommand: ghr -draft -n ${CIRCLE_TAG} -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ~/artifacts

  publish_pypi:
    steps:
      - setup
      - buildevents/berun:
          bename: poetry_publish
          becommand: poetry publish --build -u honeycomb -p ${PYPI_PASSWORD}

# required as all of the jobs need to have a tag filter for some reason
tag_filters: &tag_filters
  filters:
    tags:
      only: /.*/

jobs:
  setup_trace:
    executor: python
    steps:
      - buildevents/start_trace
  watch:
    executor: python
    steps:
      - buildevents/watch_build_and_finish
  test:
    parameters:
      python-version:
        type: string
    docker:
      - image: circleci/python:<<parameters.python-version>>
    steps:
      - buildevents/with_job_span:
          steps:
            - runtests
  build:
    executor: python
    steps:
      - buildevents/with_job_span:
          steps:
            - build
  publish_github:
    executor: github
    steps:
      - buildevents/with_job_span:
          steps:
            - publish_github
  publish_pypi:
    executor: python
    steps:
      - buildevents/with_job_span:
          steps:
            - publish_pypi

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - setup_trace:
          filters:
            tags:
              only: /.*/
      - test:
          matrix:
            parameters:
              python-version: ["3.7", "3.8", "3.9", "3.10"]
          filters:
            tags:
              only: /.*/
          requires:
            - setup_trace
      - build:
          filters:
            tags:
              only: /.*/
          requires:
            - test

  build_libhoney:
    jobs:
      - setup_trace:
          filters:
            tags:
              only: /.*/
      - test:
          matrix:
            parameters:
              python-version: ["3.7", "3.8", "3.9", "3.10"]
          filters:
            tags:
              only: /.*/
          requires:
            - setup_trace
      - build:
          filters:
            tags:
              only: /.*/
          requires:
            - test
      - publish_github:
          context: Honeycomb Secrets for Public Repos
          requires:
            - build
          filters:
            tags:
              only: /v[0-9].*/
            branches:
              ignore: /.*/
      - publish_pypi:
          context: Honeycomb Secrets for Public Repos
          requires:
            - build
          filters:
            tags:
              only: /v[0-9].*/
            branches:
              ignore: /.*/
