version: '3'

services:
  app:
    build: .
    ports:
    - "5000:5000"
    networks:
    - main
    environment:
      DB_HOST: db
      HONEYCOMB_API_KEY:
    restart: on-failure
    depends_on:
      - "db"

  db:
    image: mysql
    networks:
    - main
    volumes:
    - example-python-api:/var/lib
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "example-python-api"
    command: ["mysqld", "--authentication_policy", "mysql_native_password"]

volumes:
  example-python-api:

networks:
  main:
    driver: bridge
